title: Poon Xuan Ling
logo: /assets/img/headshot_circle.png
description: Data enthusiast committed to growth and learning. Eager to tackle exciting projects that advance my skills in the dynamic world of data.
show_downloads: true
theme: jekyll-theme-minimal
